DROP TABLE IF EXISTS HISTOGRAMRESULT;
DROP TABLE IF EXISTS CAP;
CREATE TABLE CAP (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  fileName VARCHAR(250) NOT NULL,
  capName VARCHAR(250) NOT NULL,
  create_time TIMESTAMP NOT NULL
);

CREATE TABLE HISTOGRAMRESULT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  firstCapId INT NOT NULL,
  secondCapId INT NOT NULL,
  correlation FLOAT NOT NULL,
  chisquare FLOAT NOT NULL,
  intersection FLOAT NOT NULL,
  bhattacharyya FLOAT NOT NULL
);