DROP TABLE IF EXISTS CAP;
DROP TABLE IF EXISTS HISTOGRAMRESULT;
CREATE TABLE CAP (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  path VARCHAR(250) NOT NULL,
  create_time TIMESTAMP NOT NULL
);

CREATE TABLE HISTOGRAMRESULT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  correlation FLOAT NOT NULL,
  chisquare FLOAT NOT NULL,
  intersection FLOAT NOT NULL,
  bhattacharyya FLOAT NOT NULL
);